name: Code quality and deploy

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build
      - name: biome check
        run: bun run check:ci
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload --message "Deployed pages by GitHub Actions branch ${{ github.ref_name }}"
      - name: Upload and get preview URL
        id: deploy
        run: |
          DEPLOY_OUTPUT=$(npx wrangler versions upload --message "Deployed from GitHub Actions" --output json)
          echo "$DEPLOY_OUTPUT"
          DEPLOYMENT_URL=$(echo "$DEPLOY_OUTPUT" | jq -r '.preview_url')
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Create PR comment
        run: |
          cat <<EOF > comment.md
          ## 🚀 Deploying yossy.dev with Cloudflare Workers
          <table>
            <tr>
              <th scope="row">Workers Preview URL</th>
              <td><a href="${{ steps.deploy.outputs.deployment_url }}" target="_blank" rel="noopener noreferrer">${{ steps.deploy.outputs.deployment_url }}</a></td>
            </tr>
          </table>
          EOF
