name: Code quality and deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build
      - name: biome check
        run: bun run check:ci
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload --message "Deployed pages by GitHub Actions branch ${{ github.ref_name }}"
      - name: Create comment file
        id: create-comment-file
        env:
          DEPLOYMENT_URL: "${{ steps.deploy-workers-preview.outputs.deployment-url }}"
          PAGES_DEPLOYMENT_URL: "${{ steps.deploy-pages-preview.outputs.deployment-url }}"
          PAGES_BRANCH_URL: "${{ steps.deploy-pages-preview.outputs.deployment-alias-url }}"
        run: |
          cat  << EOF > comment.md
          ## 🚀 Deploying ${{ github.event.repository.name }} with Cloudflare Workers
          <table>
            <tr>
              <th scope="row">Workers Preview URL</th>
              <td><a href="$DEPLOYMENT_URL" target="_blank" rel="noopener noreferrer">$DEPLOYMENT_URL</a></td>
            </tr>
            <tr>
              <th scope="row">Pages Preview URL</th>
              <td><a href="$PAGES_DEPLOYMENT_URL" target="_blank" rel="noopener noreferrer">$PAGES_DEPLOYMENT_URL</a></td>
            </tr>
            <tr>
              <th scope="row">Pages branch URL</th>
              <td><a href="$PAGES_BRANCH_URL" target="_blank" rel="noopener noreferrer">$PAGES_BRANCH_URL</a></td>
            </tr>
          </table>
          EOF
